M48
; DRILL file {KiCad 8.0.7} date 2026-03-12T18:24:49-0700
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-03-12T18:24:49-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.500
%
G90
G05
T1
X202.58Y-105.525
X202.58Y-110.375
T2
X205.61Y-105.225
X205.61Y-110.675
T3
X97.79Y-76.2
X207.01Y-76.2
X207.01Y-123.19
M30
